### ISSUE TITLE
Whiteboard Rendering

### ISSUE THREAD

**Issue by Bitheral** [MrCrayfish/MrCrayfishFurnitureMod-CE#1]
If you put a whiteboard, let's say, north then place one west the north placed whiteboard will think that the north and west are connected.

![2016-02-13_00 46 51](https://cloud.githubusercontent.com/assets/11707193/13024363/5446e77e-d1eb-11e5-9425-1994dccbdbae.png)

**Comment by MrCrayfish** [comment]
Thank you! An update should come out within a day :)

**Comment by MrCrayfish** [comment]
Fixed!
