### ISSUE TITLE
Painting deleted w/ Canvas

### ISSUE THREAD

**Issue by WenXin20** [MrCrayfish/MrCrayfishFurnitureMod-CE#2]
If a painting is placed on the canvas and then you break the canvas, the painting is deleted and you don't get the item back.

**Comment by MrCrayfish** [comment]
Thank you! Will be fixed in next update :pizza:

**Comment by WenXin20** [comment]
Thanks. :)

**Comment by MrCrayfish** [comment]
Fixed :)
